### PR TITLE
KSP-AVC is very picky about commas

### PR DESCRIPTION
**Pull request by Olympic1**
You forgot some commas that fails the version checking

### CODE REVIEW

**Comment by BenjaminCronin** [comment]
Does this mean you downloaded the mod? 👍 Thanks for alerting me to this!

**Comment by Olympic1** [comment]
Yes, wanted to test it out

**Comment by BenjaminCronin** [comment]
Cool, thanks! Is it working out? Everything looking good?

**Comment by Olympic1** [comment]
Yes, haven't found any problems yet, except for this file.

**Comment by BenjaminCronin** [comment]
Ok, thanks! I'll merge this commit, thanks for your help.

**Comment by Olympic1** [comment]
Thx

**Comment by BenjaminCronin** [comment]
I'll probably put this in the next release, and there is a lot of weird stuff I need to do with the files. Thanks again, and spread the word!

**Pull request merged**
